keep_features1 = [
'user_video_create_frequency_f2','user_app_launch_var_b3',
'user_user_activity_rate_f3_resInv', 'user_user_activity_rate_b9', 'user_user_activity_rate_f0',
'user_app_launch_rate_b8','user_user_activity_day_b8','user_app_launch_rate_f0',
'user_app_launch_rate_b0_resInv','user_user_activity_day_f2_resInv','user_user_activity_day_f2',
'user_app_launch_rate_f4_resInv','user_action3_page2_ratio','user_user_activity_frequency_f3',
'user_app_launch_rate_b7_resInv', 'user_app_launch_rate_f0_resInv','user_user_activity_day_b1',
'user_user_activity_frequency_b11','user_video_ratio','user_user_activity_mod_var',
'user_user_activity_rate_b8_resInv', 'user_user_activity_rate_f0_resInv','user_author_rate',
'user_page4_ratio','user_user_activity_frequency_b5','user_user_activity_lsbm',
'user_video_create_register_device_ratio','user_user_activity_tras','user_video_create_gap_b8',
'user_video_create_rate_b6','user_user_activity_rate_b9_resInv', 'user_video_rate_resInv',
'user_video_create_day_f0','user_app_launch_var_b12','user_action2_page0_ratio',
'user_video_create_rate_b0_resInv','user_app_launch_abs_energy',
'user_app_launch_mod_var', 'user_app_launch_mean','register_day_type_ratio',
'user_app_launch_bent','user_app_launch_only_in_weekend','user_user_activity_rate_b0','user_app_launch_rate_b1_resInv',
'user_action3_page1_ratio','register_day','user_video_create_cam','user_video_create_day_f2',
'user_user_activity_device_type_ratio','user_app_launch_rate_b5', 'user_user_activity_day_b4',
'user_user_activity_workday_weekend_rate_ratio','register_day_register_type_device_ratio',
'user_user_activity_var_b6','register_day_device_ratio','user_user_activity_var_b3',
'user_user_activity_weekend_day','user_video_create_day_f0_resInv','user_user_activity_rate_b0_resInv',
'user_action0_page2_ratio','user_user_activity_only_in_weekend','user_action1_page3_ratio',
'user_page0_action5_ratio','user_author_ratio','user_action2_page1_ratio',
'user_video_create_mode', 'user_app_launch_rate_b0','user_video_create_cid_ce', 'user_user_activity_rate_f5_resInv',
'user_user_activity_bent','user_video_create_first_time','user_app_launch_first_time',
'register_type_device','user_app_launch_workday_rate','user_user_activity_rate_b2_resInv',
'user_user_activity_day_b9_resInv','user_page4_action0_ratio',
'user_page2_action0_ratio', 'user_video_create_last_time',
'user_user_activity_first_time','user_video_create_frequency_b6','user_video_create_var',
'user_user_activity_day_var_b9','user_page3_action3_ratio','user_video_create_frequency_b12',
'user_video_create_rate_f4','user_app_launch_gap_b6','user_video_create_frequency_f4',
'user_app_launch_video_ratio','video_author_ratio',
'user_user_activity_day_f1_resInv','user_page3_ratio','user_in_author_rate','user_action2_page3_ratio',
'user_app_launch_rate_f1','user_action1_page0_ratio', 'user_action0_page0_ratio',
'user_video_create_lsbm','user_user_activity_day_f5','user_video_create_rate_f2',
'user_video_create_tras','user_user_activity_var_lt_std','user_video_create_day_f2_resInv',
'user_page3_action0_ratio','user_action_type1_ratio','user_action1_page4_ratio','user_video_create_day_b6',
'user_video_create_gap_b5','user_app_launch_activity_ratio','user_author_rate_resInv',
'user_video_create_rbrs','user_video_create_prda','user_video_create_rate_b12',
'user_user_activity_gap_b6','user_page1_action1_ratio',
'user_user_activity_day_f0_resInv','user_user_activity_day_b4_resInv','user_action2_page4_ratio',
'user_app_launch_register_device_ratio','user_user_activity_last_time',
'user_user_activity_mean_change','user_action2_page2_ratio','user_app_launch_gap_b12',
'user_video_create_day_var_b11','user_user_activity_prda','user_user_activity_abs_energy',
'user_app_launch_autocorr','user_page2_action1_ratio','register_day_device_type_register_ratio',
'user_page3_action1_ratio','user_user_activity_frequency_f4','user_user_activity_day_b0',
'user_app_launch_tras','user_user_activity_gap_b12','user_video_create_rate_b12_resInv',
'user_app_launch_device_register_ratio','user_user_activity_weekend_rate','user_page2_action2_ratio',
'user_app_launch_mean_change','user_video_create_gap','user_page2_action3_ratio',
'user_user_activity_min','user_video_create_device_register_ratio','user_user_activity_workday_rate',
'user_user_activity_lsam','user_video_create_rate_f2_resInv','user_user_activity_rate_b1',
'user_action3_page3_ratio','user_page0_action1_ratio','user_user_activity_mode', 'user_app_launch_gap_b3',
'user_user_activity_mean','user_page0_action0_ratio','user_user_activity_rbrs','user_user_activity_gap_b3',
'user_app_launch_var_b6','user_user_activity_register_type_ratio','user_video_create_day_var_b8',
'user_action1_page1_ratio','user_page2_action5_ratio',
'user_user_activity_weekend_frequency','user_action3_page0_ratio','user_user_activity_workday_weekend_day_ratio',
'user_page4_action3_ratio','user_video_create_frequency_b3','user_user_activity_autocorr',
'user_action3_page4_ratio','user_app_launch_workday_weekend_rate_ratio','user_page1_action0_ratio',
'user_video_create_device_type_ratio','user_page0_action3_ratio',
'user_user_activity_device_register_ratio','user_app_launch_gap_b9','user_page1_action3_ratio',
'user_video_create_register_type_ratio','user_video_create_min','user_user_activity_var_b9',
'user_app_launch_rbrs','user_user_activity_gap_b9','user_video_create_day_var_b5',
'user_user_activity_cid_ce','user_user_activity_frequency_f2',
'user_action1_page2_ratio','user_video_create_max','user_video_create_rate_b0',
'user_user_activity_workday_frequency','user_video_create_rate_b3',
'user_user_activity_day_b0_resInv','user_app_launch_last_time',
    ]
print(len(keep_features1))
print(len(list(set(keep_features1))))
print([f for f in keep_features1 if keep_features1.count(f)>1])
keep_features2 = [
'user_video_create_frequency_f2','user_app_launch_var_b3',
'user_user_activity_rate_f1', 'user_user_activity_rate_f2',
'user_app_launch_rate_b6','user_user_activity_day_b11','user_app_launch_rate_b11',
'user_app_launch_rate_b0_resInv','user_user_activity_day_f3_resInv','user_user_activity_frequency_f3',
'user_user_activity_day_f4_resInv','user_action3_page2_ratio',
'user_app_launch_rate_b6_resInv', 'user_app_launch_rate_b10_resInv','user_user_activity_day_b1',
'user_user_activity_frequency_b9', 'user_user_activity_frequency_f0','user_user_activity_day_var',
'user_user_activity_rate_b7_resInv', 'user_user_activity_rate_b5_resInv','user_author_rate',
'user_action0_page4_ratio','user_user_activity_frequency_b5',
'user_user_activity_lsbm','user_video_create_register_device_ratio','user_user_activity_tras',
'user_video_create_gap_b8','user_video_create_rate_b6','user_user_activity_rate_b11_resInv', 'user_user_activity_rate_b6_resInv',
'user_video_create_day_f2','user_user_activity_var_b12','user_action2_page0_ratio',
'user_video_create_rate_b0_resInv','user_user_activity_rate_b2','user_app_launch_abs_energy',
'user_app_launch_var', 'user_user_activity_max', 'register_type_ratio', 'user_app_launch_bent',
'user_app_launch_only_in_weekend','user_user_activity_rate_b0','user_app_launch_rate_b1_resInv',
'user_action3_page1_ratio','register_day','user_video_create_cbm',
'user_user_activity_register_device_ratio','user_user_activity_day_b4', 'user_app_launch_rate_b2',
'user_user_activity_workday_weekend_rate_ratio','register_day_register_type_device_ratio',
'user_user_activity_day_var_b6','register_type_device_ratio','user_user_activity_var_b3',
'user_user_activity_weekend_day','user_video_create_day_b6_resInv','user_user_activity_rate_b0_resInv',
'user_action_type2_ratio','user_user_activity_only_in_weekend','user_action1_page3_ratio',
'user_page0_action5_ratio','user_author_ratio','user_action2_page1_ratio',
'user_video_create_mean', 'user_app_launch_rate_b0','user_video_create_cid_ce',
'user_user_activity_bent', 'user_video_create_first_time','user_user_activity_rate_b2_resInv',
'register_type_device','user_app_launch_workday_rate','user_app_launch_first_time',
'user_user_activity_day_b9_resInv','user_page4_action0_ratio',
'user_page2_action0_ratio','user_video_create_last_time',
'user_user_activity_first_time','user_video_create_frequency_b6','user_video_create_var',
'user_user_activity_day_var_b9','user_page3_action3_ratio','user_video_create_frequency_b12',
'user_video_create_rate_f4','user_app_launch_gap_b6','user_video_create_frequency_f4',
'user_app_launch_video_ratio','video_author_ratio',
'user_user_activity_day_f1_resInv','user_page3_ratio','user_in_author_rate','user_action2_page3_ratio',
'user_app_launch_rate_f5','user_app_launch_rate_f4','user_action1_page0_ratio','user_action_type0_ratio',
'user_video_create_lsbm','user_user_activity_day_f5','user_video_create_tras',
'user_user_activity_var_lt_std','user_video_create_day_f2_resInv','user_app_launch_var_lt_std',
'user_page3_action0_ratio','user_page1_ratio','user_action1_page4_ratio','user_video_create_day_b6',
'user_video_create_gap_b5','user_app_launch_activity_ratio','user_author_rate_resInv',
'user_video_create_rbrs','user_video_create_prda','user_video_create_rate_b9',
'user_user_activity_gap_b6','user_page1_action1_ratio',
'user_user_activity_day_f0_resInv','user_user_activity_day_b4_resInv','user_action2_page4_ratio',
'user_app_launch_register_device_ratio','user_user_activity_last_time',
'user_user_activity_mean_change','user_action2_page2_ratio','user_app_launch_gap',
'user_video_create_day_var_b11','user_user_activity_prda','user_user_activity_abs_energy',
'user_app_launch_autocorr','user_page2_action1_ratio','register_day_device_type_register_ratio',
'user_page3_action1_ratio','user_user_activity_frequency_f4','user_user_activity_day_b0',
'user_app_launch_tras','user_user_activity_gap','user_video_create_rate_b6_resInv',
'device_type_register_ratio','user_user_activity_weekend_rate','user_page2_action2_ratio',
'user_video_create_abs_energy','user_app_launch_mean_change','user_video_create_gap',
'user_page2_action3_ratio','user_user_activity_min','user_video_create_device_register_ratio',
'user_user_activity_workday_rate','user_user_activity_lsam','user_video_create_rate_f2_resInv',
'user_user_activity_rate_b1','user_action3_page3_ratio','user_page0_action1_ratio','user_user_activity_mode',
'user_user_activity_mean','user_page0_action0_ratio','user_user_activity_rbrs',
'user_app_launch_var_b6','user_user_activity_register_type_ratio','user_video_create_day_var_b8',
'user_action1_page1_ratio','user_page2_action5_ratio',
'user_user_activity_weekend_frequency','user_action3_page0_ratio','user_user_activity_workday_weekend_day_ratio',
'user_page4_action3_ratio','user_video_create_frequency_b3','user_user_activity_autocorr',
'user_action3_page4_ratio','user_app_launch_workday_weekend_rate_ratio','user_page1_action0_ratio',
'user_video_create_device_type_ratio','user_page0_action3_ratio','user_page4_ratio',
'user_user_activity_device_register_ratio','user_app_launch_gap_b9','user_page1_action3_ratio',
'user_video_create_register_type_ratio','user_video_create_min','user_user_activity_var_b9',
'user_app_launch_rbrs','user_user_activity_gap_b9','user_video_create_day_var_b5',
'user_user_activity_cid_ce','user_user_activity_frequency_f2',
'user_action1_page2_ratio','user_video_create_max','user_video_create_rate_b0',
'user_user_activity_workday_frequency','user_video_create_rate_b3',
'user_user_activity_day_b0_resInv','user_app_launch_last_time',
]
print(len(keep_features2))
print(len(list(set(keep_features2))))
print([f for f in keep_features2 if keep_features2.count(f)>1])
keep_features3 = [
'user_video_create_frequency_f2','user_app_launch_var_b3',
'user_user_activity_rate_f3', 'user_user_activity_rate_f4_resInv',
'user_app_launch_rate_b9','user_user_activity_day_b10', 'user_user_activity_day_b6',
'user_app_launch_rate_b0_resInv','user_user_activity_day_f3_resInv','user_user_activity_frequency_f3',
'user_app_launch_rate_f3', 'user_user_activity_day_f1','user_action3_page2_ratio',
'user_app_launch_rate_b11_resInv', 'user_app_launch_rate_b9_resInv','user_user_activity_day_b2',
'user_user_activity_frequency_b10','user_user_activity_frequency_b6','user_user_activity_var',
'user_video_rate_resInv', 'user_user_activity_rate_b10_resInv','user_author_rate',
'user_video_create_register_device_ratio',
'user_user_activity_lsbm','user_user_activity_tras','user_video_create_gap_b8',
'user_video_create_rate_b6', 'user_user_activity_rate_b7_resInv',
'user_video_create_day_f4','user_user_activity_day_var_b12','user_action2_page0_ratio',
'user_video_create_rate_b0_resInv','user_user_activity_rate_b3','user_app_launch_abs_energy',
'user_app_launch_median','user_app_launch_var','user_app_launch_register_type_ratio',
'user_app_launch_cid_ce','user_app_launch_only_in_weekend','user_user_activity_rate_b0',
'user_user_activity_day_b1_resInv','user_action3_page1_ratio','register_day',
'user_video_create_day_f0','user_video_create_day_f2','user_user_activity_register_device_ratio',
'user_app_launch_rate_b3',  'user_user_activity_day_b4','user_user_activity_workday_weekend_rate_ratio',
'register_day_register_type_device_ratio','user_user_activity_day_var_b6','user_app_launch_device_type_ratio',
'user_user_activity_day_var_b3','user_video_create_day_b3_resInv','user_user_activity_rate_b1_resInv',
'user_page2_ratio','user_user_activity_only_in_weekend','user_action1_page3_ratio',
'user_page0_action5_ratio','user_author_ratio','user_action2_page1_ratio',
'user_video_create_median', 'user_app_launch_rate_b0','user_video_create_bent',
'user_user_activity_bent', 'user_video_create_first_time','user_app_launch_first_time',
'register_type_device','user_app_launch_workday_rate','user_user_activity_rate_b2_resInv',
'user_user_activity_day_b9_resInv','user_page4_action0_ratio',
'user_page2_action0_ratio','user_video_create_last_time',
'user_user_activity_register_time','user_video_create_frequency_b6','user_video_create_var',
'user_app_launch_var_b9','user_page3_action3_ratio','user_video_create_frequency_b9',
'user_video_create_rate_f4','user_app_launch_gap_b6','user_video_create_frequency_f4',
'user_app_launch_video_ratio','video_author_ratio',
'user_user_activity_day_f1_resInv','user_action0_page3_ratio','user_in_author_rate',
'user_action2_page3_ratio', 'user_app_launch_rate_f2',
'user_action1_page0_ratio','user_action_type0_ratio','user_video_create_frequency_f0',
'user_user_activity_day_f5','user_video_create_tras','user_user_activity_var_lt_std',
'user_video_create_day_f2_resInv','user_app_launch_var_lt_std','user_page3_action0_ratio',
'user_action_type1_ratio','user_action1_page4_ratio','user_video_create_day_b9','user_video_create_day_b3',
'user_app_launch_activity_ratio','user_author_rate_resInv','user_video_create_rbrs',
'user_video_create_prda','user_user_activity_gap_b6',
'user_page1_action1_ratio','user_user_activity_day_f0_resInv',
'user_user_activity_day_b4_resInv','user_action2_page4_ratio','user_user_activity_last_time',
'user_user_activity_mean_change','user_action2_page2_ratio',
'user_app_launch_gap','user_video_create_var_b11','user_user_activity_prda',
'user_user_activity_abs_energy','user_app_launch_autocorr','user_page2_action1_ratio',
'register_day_device_type_register_ratio','user_page3_action1_ratio','user_user_activity_frequency_f5',
'user_user_activity_day_b0','user_app_launch_tras','user_user_activity_gap','user_video_create_rate_f0_resInv',
'device_type_register_ratio','user_user_activity_weekend_rate','user_page2_action2_ratio',
'user_video_create_abs_energy','user_app_launch_mean_change','user_video_create_gap',
'user_page2_action3_ratio','user_user_activity_min','user_video_create_device_register_ratio',
'user_user_activity_workday_rate','user_user_activity_lsam','user_video_create_rate_f2_resInv',
'user_user_activity_rate_b2','user_action3_page3_ratio','user_page0_action1_ratio','user_user_activity_mode',
'user_user_activity_mean','user_page0_action0_ratio','user_user_activity_rbrs',
'user_app_launch_var_b6','user_user_activity_register_type_ratio', 'user_video_create_var_b8',
'user_action1_page1_ratio','user_page2_action5_ratio',
'user_user_activity_weekend_frequency','user_action3_page0_ratio','user_user_activity_workday_weekend_day_ratio',
'user_page4_action3_ratio','user_video_create_frequency_b3','user_user_activity_autocorr',
'user_action3_page4_ratio','user_app_launch_workday_weekend_rate_ratio','user_page1_action0_ratio',
'user_video_create_device_type_ratio','user_page0_action3_ratio','user_user_activity_device_register_ratio',
'user_app_launch_gap_b9','user_page1_action3_ratio','user_video_create_register_type_ratio',
'user_video_create_min','user_user_activity_day_var_b9', 'user_app_launch_rbrs',
'user_user_activity_gap_b9','user_video_create_var_b5','user_user_activity_cid_ce',
'user_user_activity_frequency_f1','user_action1_page2_ratio',
'user_video_create_rate_b0','user_user_activity_workday_frequency',
'user_video_create_rate_b3','user_user_activity_day_b0_resInv','user_app_launch_last_time',
]
print(len(keep_features3))
print(len(list(set(keep_features3))))
print([f for f in keep_features3 if keep_features3.count(f)>1])
keep_features4 = [
'user_video_create_frequency_f2','user_app_launch_var_b3',
'user_video_rate', 'user_user_activity_rate_f2_resInv',
'user_app_launch_rate_b10', 'user_app_launch_rate_b5', 'user_user_activity_day_b7',
'user_app_launch_rate_b0_resInv', 'user_app_launch_rate_f2_resInv',
'user_app_launch_rate_f5_resInv', 'user_user_activity_day_f4','user_action3_page2_ratio',
'user_user_activity_frequency_f3','user_app_launch_rate_b4_resInv', 'user_app_launch_rate_b5_resInv',
'user_user_activity_gap_b3','user_user_activity_frequency_b8','user_video_ratio','user_user_activity_var',
'user_user_activity_rate_b9_resInv', 'user_user_activity_rate_b4_resInv','user_author_rate',
'user_action0_page4_ratio','user_user_activity_frequency_b5',
'user_user_activity_lsbm','user_video_create_register_device_ratio','user_user_activity_tras',
'user_video_create_gap_b11','user_video_create_rate_b9','user_user_activity_rate_b5_resInv', 'user_user_activity_rate_b8_resInv',
'user_video_create_day_f4_resInv','user_user_activity_day_var_b12','user_action2_page0_ratio',
'user_video_create_rate_b0_resInv','user_user_activity_frequency_b2','user_app_launch_abs_energy',
'user_app_launch_var', 'user_user_activity_median','user_app_launch_register_type_ratio',
'user_app_launch_cid_ce','user_app_launch_only_in_weekend','user_user_activity_rate_b0',
'user_user_activity_day_b1_resInv','user_action3_page1_ratio','register_day',
'user_video_create_day_b12','user_video_create_day_f2','user_user_activity_device_type_ratio',
'user_user_activity_workday_weekend_rate_ratio','register_day_register_type_device_ratio',
'user_user_activity_var_b6','device_type_ratio','user_user_activity_day_var_b3',
'user_app_launch_weekend_rate','user_video_create_day_b9_resInv','user_user_activity_rate_b0_resInv',
'user_page2_ratio','user_user_activity_only_in_weekend','user_action1_page3_ratio',
'user_page0_action5_ratio','user_author_ratio','user_action2_page1_ratio',
'user_video_create_mode', 'user_app_launch_rate_b0','user_video_create_bent',
'user_user_activity_bent','user_video_create_register_time','user_app_launch_register_time',
'register_type_device','user_app_launch_workday_rate','user_user_activity_rate_b2_resInv',
'user_user_activity_day_b9_resInv','user_page4_action0_ratio',
'user_page2_action0_ratio','user_video_create_last_time',
'user_user_activity_register_time','user_video_create_frequency_b6','user_video_create_day_var',
'user_app_launch_var_b9','user_page3_action3_ratio','user_video_create_frequency_b9',
'user_video_create_rate_f4_resInv','register_type_device_ratio','user_app_launch_gap_b6',
'user_video_create_frequency_f4','user_app_launch_video_ratio','video_author_ratio',
'user_app_launch_rate_f1_resInv','user_action0_page3_ratio',
'user_in_author_rate','user_action2_page3_ratio',
'user_action1_page0_ratio','user_page0_ratio','user_video_create_frequency_f0','user_user_activity_day_f5',
'user_video_create_tras','user_user_activity_var_lt_std','user_video_create_day_f2_resInv',
'user_app_launch_var_lt_std','user_page3_action0_ratio','user_action0_page1_ratio','user_action1_page4_ratio',
'user_video_create_day_b9','user_video_create_day_b3','user_app_launch_activity_ratio','user_author_rate_resInv',
'user_video_create_rbrs','user_video_create_prda', 'user_video_create_rate_f0','user_user_activity_gap_b6',
'user_page1_action1_ratio','user_user_activity_day_f0_resInv',
'user_user_activity_day_b4_resInv','user_action2_page4_ratio','user_user_activity_last_time',
'user_user_activity_mean_change','user_action2_page2_ratio',
'user_app_launch_gap_b12','user_video_create_var_b11','user_user_activity_prda',
'user_user_activity_abs_energy','user_app_launch_autocorr','user_page2_action1_ratio',
'register_day_device_type_register_ratio','user_page3_action1_ratio','user_user_activity_frequency_f5',
'user_user_activity_day_b0','user_app_launch_tras','user_user_activity_gap','user_video_create_rate_b9_resInv',
'user_app_launch_device_register_ratio','user_user_activity_weekend_rate','user_page2_action2_ratio',
'user_video_create_abs_energy','user_app_launch_mean_change','user_page2_action3_ratio',
'user_user_activity_min','user_video_create_device_register_ratio','user_user_activity_workday_day',
'user_user_activity_lsam','user_video_create_rate_f2_resInv','user_user_activity_frequency_b1',
'user_action3_page3_ratio','user_page0_action1_ratio','user_user_activity_mode',
'user_user_activity_mean','user_page0_action0_ratio','user_user_activity_rbrs',
'user_app_launch_var_b6','user_user_activity_register_type_ratio', 'user_video_create_var_b8',
'user_action1_page1_ratio','user_page2_action5_ratio',
'user_user_activity_weekend_frequency','user_action3_page0_ratio','user_user_activity_workday_weekend_day_ratio',
'user_page4_action3_ratio','user_video_create_frequency_b3','user_user_activity_autocorr',
'user_action3_page4_ratio','user_app_launch_workday_weekend_rate_ratio','user_page1_action0_ratio',
'user_video_create_device_type_ratio','user_page0_action3_ratio','user_user_activity_device_register_ratio',
'user_app_launch_gap_b9','user_page1_action3_ratio','user_video_create_register_type_ratio',
'user_video_create_min','user_user_activity_day_var_b9', 'user_app_launch_rbrs',
'user_user_activity_gap_b9','user_video_create_var_b5','user_user_activity_rate_b1',
'user_user_activity_cid_ce','user_user_activity_frequency_f1',
'user_action1_page2_ratio','user_video_create_rate_b0','user_user_activity_workday_frequency',
'user_video_create_rate_b3','user_user_activity_day_b0_resInv',
'user_app_launch_last_time',
]
print(len(keep_features4))
print(len(list(set(keep_features4))))
print([f for f in keep_features4 if keep_features4.count(f)>1])
keep_features5 = [
'user_video_create_frequency_f2','user_app_launch_var_b3',
'user_user_activity_rate_b10', 'user_user_activity_rate_b11',
'user_app_launch_rate_b7', 'user_app_launch_cam', 'user_user_activity_day_b9',
'user_app_launch_rate_b0_resInv', 'user_app_launch_rate_f2_resInv','user_user_activity_day_f3',
'user_user_activity_day_f5_resInv','user_action3_page2_ratio','user_user_activity_frequency_f3',
'user_app_launch_rate_b8_resInv', 'user_app_launch_rate_b3_resInv','user_app_launch_rate_b1',
'user_user_activity_frequency_b7', 'user_video_ratio','user_user_activity_mod_var',
'user_user_activity_rate_b11_resInv', 'user_user_activity_rate_b6_resInv','user_author_rate',
'user_page4_ratio','user_user_activity_tras',
'user_user_activity_lsbm','user_video_create_register_device_ratio','user_video_create_gap_b11',
'user_video_create_rate_b9','user_user_activity_rate_f0_resInv', 'user_video_create_day_f0',
'user_app_launch_var_b12','user_action2_page0_ratio','user_video_create_rate_b0_resInv',
'user_user_activity_rate_b4','user_app_launch_abs_energy','user_app_launch_max','user_app_launch_mod_var',
'register_day_type_ratio','user_app_launch_cid_ce','user_app_launch_only_in_weekend',
'user_user_activity_rate_b0','user_app_launch_rate_b2_resInv','user_action3_page1_ratio',
'register_day','user_video_create_day_f2','user_user_activity_device_type_ratio',
'user_user_activity_day_b3','user_app_launch_rate_b4','user_user_activity_workday_weekend_rate_ratio',
'register_day_register_type_device_ratio','user_user_activity_var_b6','device_type_ratio',
'user_user_activity_day_var_b3','user_app_launch_weekend_rate','user_video_create_day_b12_resInv',
'user_user_activity_rate_b1_resInv','user_action0_page2_ratio','user_user_activity_only_in_weekend',
'user_action1_page3_ratio','user_page0_action5_ratio','user_author_ratio','user_action2_page1_ratio',
'user_video_create_mode', 'user_app_launch_rate_b0','user_video_create_cid_ce',
'user_user_activity_bent','user_video_create_register_time','user_app_launch_register_time',
'register_type_device','user_app_launch_workday_rate','user_user_activity_rate_b2_resInv',
'user_user_activity_day_b9_resInv','user_page4_action0_ratio',
'user_page2_action0_ratio','user_video_create_last_time',
'user_user_activity_first_time','user_video_create_frequency_b6','user_video_create_day_var',
'user_app_launch_var_b9','user_page3_action3_ratio','user_video_create_frequency_b9','user_video_create_rate_f4_resInv',
'user_app_launch_gap_b6','user_video_create_frequency_f4','user_app_launch_video_ratio','video_author_ratio',
'user_app_launch_rate_f1_resInv','user_action_type3_ratio','user_in_author_rate',
'user_action2_page3_ratio','user_action1_page0_ratio','user_page0_ratio',
'user_video_create_frequency_f0','user_user_activity_day_f5', 'user_video_create_tras','user_user_activity_var_lt_std',
'user_video_create_day_f2_resInv','user_app_launch_var_lt_std','user_page3_action0_ratio','user_action0_page1_ratio',
'user_action1_page4_ratio','user_video_create_day_b6','user_video_create_gap_b5','user_app_launch_activity_ratio',
'user_author_rate_resInv','user_video_create_rbrs','user_video_create_prda','user_video_create_rate_f0',
'user_user_activity_gap_b6','user_page1_action1_ratio',
'user_user_activity_day_f0_resInv','user_user_activity_day_b4_resInv','user_action2_page4_ratio',
'user_user_activity_last_time','user_user_activity_mean_change',
'user_action2_page2_ratio','user_app_launch_gap_b12','user_video_create_var_b11','user_user_activity_prda',
'user_user_activity_abs_energy','user_app_launch_autocorr','user_page2_action1_ratio',
'register_day_device_type_register_ratio','user_page3_action1_ratio','user_user_activity_frequency_f4',
'user_user_activity_day_b0','user_app_launch_tras','user_user_activity_gap_b12','user_video_create_rate_b3_resInv',
'user_app_launch_device_register_ratio','user_user_activity_weekend_rate','user_page2_action2_ratio',
'user_video_create_abs_energy','user_app_launch_mean_change','user_video_create_gap',
'user_page2_action3_ratio','user_user_activity_min','user_video_create_device_register_ratio',
'user_user_activity_workday_day','user_user_activity_lsam','user_video_create_rate_f2_resInv',
'user_user_activity_rate_b1','user_action3_page3_ratio','user_page0_action1_ratio','user_user_activity_mode',
'user_user_activity_mean','user_page0_action0_ratio','user_user_activity_rbrs',
'user_app_launch_var_b6','user_user_activity_register_type_ratio','user_video_create_day_var_b8',
'user_action1_page1_ratio','user_page2_action5_ratio',
'user_user_activity_weekend_frequency','user_action3_page0_ratio','user_user_activity_workday_weekend_day_ratio',
'user_page4_action3_ratio','user_video_create_frequency_b3','user_user_activity_autocorr',
'user_action3_page4_ratio','user_app_launch_workday_weekend_rate_ratio','user_page1_action0_ratio',
'user_video_create_device_type_ratio','user_page0_action3_ratio','user_user_activity_device_register_ratio',
'user_app_launch_gap_b9','user_page1_action3_ratio','user_video_create_register_type_ratio',
'user_video_create_min','user_user_activity_day_var_b9', 'user_app_launch_rbrs',
'user_user_activity_gap_b9','user_app_launch_gap_b3','user_video_create_var_b5','user_user_activity_cid_ce',
'user_user_activity_frequency_f1','user_action1_page2_ratio',
'user_video_create_median','user_video_create_rate_b0','user_user_activity_workday_frequency',
'user_video_create_rate_b3','user_user_activity_day_b0_resInv',
'user_app_launch_last_time',
]
print(len(keep_features5))
print(len(list(set(keep_features5))))
print([f for f in keep_features5 if keep_features5.count(f)>1])

feature_importance_lgb = []
keep_features_selected = []

features_all = list(set(keep_features1+keep_features2+keep_features3+keep_features4+keep_features5))
print("the whole length of the feature set: {}".format(len(features_all)))

zero_shap_features = [
    'user_video_create_var_lt_std', 'user_page0_action4_ratio', 'user_page1_action2_ratio',
    'user_page1_action4_ratio','user_page2_action4_ratio','user_page2_action5_ratio',
    'user_page3_action4_ratio','user_page4_action4_ratio','user_action4_page0_ratio',
    'user_action4_page1_ratio','user_action4_page2_ratio','user_action4_page3_ratio',
    'user_action4_page4_ratio','user_action5_page1_ratio', 'user_action5_page2_ratio',
    "user_app_launch_var_lt_std","user_user_activity_day_b0",]
zero_mi_features = [
    "user_action4_page3_ratio","user_action4_page1_ratio","user_page0_action4_ratio",
    'user_page2_action5_ratio','user_action5_page0_ratio','user_action2_page1',
    'user_page1_action5_ratio','user_page2_action4_ratio','user_action5_page2_ratio',
    'user_page4_action4_ratio','user_action4_page4_ratio', 'user_page1_action2_ratio',
    'user_page1_action4_ratio',
]
low_mi_features = [

]
low_shap_features = [

]
high_collinear_cols = [
    'user_action_type4_ratio', 'user_user_activity_rate_b11_resInv', 'user_user_activity_day_b8',
    'user_user_activity_rate_f0_resInv', 'user_app_launch_register_time', 'user_action0_page2_ratio',
    'user_video_create_rate_b12_resInv', 'user_user_activity_rate_f2', 'user_user_activity_day_f0',
    'user_user_activity_day_b7_resInv', 'user_user_activity_day_b6_resInv', 'user_app_launch_rate_b6_resInv',
    'user_user_activity_rate_b8_resInv', 'user_user_activity_rate_b7_resInv',
    'user_app_launch_rate_b8_resInv', 'user_action_type3_ratio', 'user_app_launch_rate_f1',
    'user_user_activity_mod_var', 'device_type_ratio', 'user_app_launch_rate_b11',
    'user_page1_ratio', 'user_user_activity_workday_rate', 'user_video_create_median',
    'user_app_launch_rate_b10', 'user_action0_page1_ratio', 'user_page0_ratio',
    'user_user_activity_rate_b11', 'user_page4_ratio', 'user_page2_ratio',
    'user_video_create_day_b12_resInv', 'user_user_activity_day_b7', 'user_action_type0_ratio',
    'user_user_activity_rate_b7', 'user_user_activity_day_b10_resInv', 'user_app_launch_rate_b10_resInv',
    'user_action0_page3_ratio', 'user_user_activity_rate_b9', 'user_app_launch_mod_var',
    'user_user_activity_day_b10', 'user_user_activity_rate_b5_resInv', 'user_user_activity_rate_b9_resInv',
    'user_video_create_rate_f0_resInv', 'user_user_activity_rate_b4_resInv', 'user_user_activity_rate_f0',
    'user_user_activity_day_b11_resInv', 'user_user_activity_day_f0_resInv',
    'user_user_activity_day_b8_resInv']
eli_features1 = [
    'user_user_activity_day_b0', 'user_page2_action5_ratio', 'user_video_create_day_f0',
    'user_video_create_day_var_b5', 'user_video_create_cid_ce', 'user_video_create_frequency_f2',
    'user_action2_page4_ratio', 'user_video_create_rbrs', 'user_video_create_min',
    'user_video_create_day_var_b8', 'user_page0_action5_ratio', 'user_user_activity_only_in_weekend',
    'user_video_create_day_var_b11', 'user_video_create_day_f2_resInv', 'user_video_create_frequency_f4',
    'user_video_create_var', 'user_user_activity_first_time', 'user_app_launch_video_ratio',
    'user_video_create_gap', 'user_user_activity_prda', 'user_action3_page3_ratio',
    'user_app_launch_rbrs', 'user_video_create_rate_b6', 'user_page4_action0_ratio',
    'user_user_activity_last_time', 'user_action1_page4_ratio', 'user_user_activity_weekend_frequency',
    'user_user_activity_var_b9', 'user_video_create_last_time', 'user_user_activity_rate_f3_resInv',
    'user_user_activity_tras','register_day', 'user_page2_action1_ratio',
    'user_video_create_rate_b3', 'user_page3_action1_ratio', 'user_author_ratio',
    'user_video_create_register_type_ratio', 'user_user_activity_rate_f0_resInv',
    'user_user_activity_weekend_day', 'user_app_launch_tras', 'user_user_activity_day_f2',
    'user_user_activity_abs_energy','user_app_launch_gap_b9', 'user_page4_ratio', 'user_user_activity_workday_weekend_rate_ratio',
    'user_user_activity_lsam', 'user_user_activity_rbrs', 'user_action0_page0_ratio',
    'user_user_activity_rate_b8_resInv', 'user_app_launch_rate_b0', 'video_author_ratio',
    'user_author_rate', 'user_user_activity_rate_b9_resInv', 'user_video_ratio',
    'user_user_activity_var_b3', 'user_author_rate_resInv', 'user_app_launch_register_device_ratio',
    'user_user_activity_rate_f0', 'user_app_launch_rate_b7_resInv', 'register_type_device']

eli_features2 = [
    'user_page2_action5_ratio', 'user_user_activity_day_b0', 'user_video_create_cbm',
    'user_action2_page4_ratio', 'user_video_create_frequency_b6', 'user_video_create_cid_ce',
    'user_page0_action5_ratio', 'user_action3_page2_ratio', 'user_video_create_frequency_f4',
    'user_video_create_gap', 'user_video_create_first_time', 'user_video_create_var',
    'user_video_create_abs_energy', 'user_user_activity_first_time', 'user_video_create_device_type_ratio',
    'user_app_launch_video_ratio', 'user_user_activity_day_b0_resInv', 'user_action1_page2_ratio',
    'user_user_activity_frequency_f2', 'user_action3_page1_ratio', 'user_video_create_device_register_ratio',
    'user_user_activity_tras', 'user_video_create_rate_f2_resInv', 'user_user_activity_day_b9_resInv',
    'user_user_activity_bent', 'user_user_activity_weekend_rate', 'user_video_create_gap_b5',
    'user_app_launch_activity_ratio', 'register_day', 'user_user_activity_weekend_frequency',
    'user_in_author_rate', 'user_user_activity_var_b9', 'user_page4_action0_ratio',
    'user_app_launch_rate_f4', 'user_video_create_register_type_ratio', 'user_video_create_last_time',
    'user_user_activity_day_f4_resInv', 'user_app_launch_rate_f5', 'user_user_activity_day_var_b6',
    'user_user_activity_mode', 'user_page4_ratio', 'user_user_activity_rate_b5_resInv',
    'user_user_activity_weekend_day', 'user_user_activity_lsam', 'user_user_activity_gap',
    'user_action_type0_ratio', 'user_user_activity_rate_f2', 'user_user_activity_day_f1_resInv',
    'user_user_activity_workday_rate', 'user_user_activity_day_f3_resInv', 'user_user_activity_max',
    'user_user_activity_day_var','user_app_launch_workday_rate', 'user_user_activity_day_var_b9',
    'user_app_launch_rate_b0', 'user_user_activity_rate_f1', 'user_user_activity_var_b3',
    'register_type_device']

eli_features3 = [
    'user_action2_page1_ratio', 'user_action2_page4_ratio', 'user_video_create_frequency_f0',
    'user_video_create_prda', 'user_video_create_frequency_f2', 'user_video_create_rate_f4',
    'user_video_create_var_b8', 'user_video_create_gap_b8', 'user_video_create_register_device_ratio',
    'user_video_create_frequency_b9', 'user_video_create_var_b11', 'user_user_activity_var_lt_std',
    'user_video_create_abs_energy', 'user_user_activity_prda', 'user_user_activity_day_b0_resInv',
    'user_video_create_rate_f0_resInv', 'user_user_activity_frequency_f3', 'user_action2_page2_ratio',
    'user_in_author_rate', 'user_video_create_frequency_b3', 'user_user_activity_weekend_frequency',
    'user_video_create_rate_f2_resInv', 'user_video_create_rate_b0', 'user_user_activity_min',
    'user_user_activity_rbrs', 'user_action3_page1_ratio', 'user_user_activity_last_time',
    'user_user_activity_frequency_f1', 'user_video_create_register_type_ratio', 'user_page2_action0_ratio',
    'user_user_activity_abs_energy', 'user_user_activity_rate_f3', 'user_app_launch_rate_b9_resInv',
    'user_user_activity_rate_f4_resInv', 'user_user_activity_autocorr', 'user_app_launch_rbrs',
    'user_user_activity_lsbm', 'user_page4_action0_ratio', 'user_user_activity_workday_rate',
    'user_app_launch_gap_b9', 'user_user_activity_day_b1_resInv', 'user_user_activity_day_b4',
    'user_user_activity_rate_b3', 'user_user_activity_day_b2', 'user_app_launch_abs_energy']
eli_features4 =  [
    'user_page2_action5_ratio', 'user_video_create_day_b9', 'user_video_create_day_f2',
    'user_action2_page1_ratio', 'user_page2_action3_ratio', 'user_video_create_frequency_f2',
    'user_video_create_var_b8', 'user_video_create_frequency_f0', 'user_video_create_day_b3',
    'user_user_activity_only_in_weekend', 'user_action3_page4_ratio', 'user_video_create_frequency_b6',
    'user_video_create_rbrs', 'user_video_create_var_b5', 'user_video_create_rate_f0',
    'user_page2_action2_ratio', 'user_video_create_register_device_ratio', 'user_app_launch_video_ratio',
    'user_action3_page1_ratio', 'user_user_activity_day_f4', 'user_user_activity_day_f5',
    'user_user_activity_frequency_f1', 'user_user_activity_frequency_f3', 'user_user_activity_rate_b8_resInv',
    'user_action1_page3_ratio', 'user_page4_action0_ratio', 'user_user_activity_tras',
    'user_page2_action1_ratio', 'user_in_author_rate', 'user_app_launch_activity_ratio',
    'user_action1_page2_ratio', 'user_user_activity_var_b6', 'user_action1_page0_ratio',
    'user_user_activity_median', 'user_author_ratio', 'user_page3_action1_ratio',
    'user_app_launch_tras', 'user_user_activity_lsbm', 'user_user_activity_rbrs',
    'user_user_activity_workday_weekend_day_ratio', 'user_page3_action0_ratio', 'user_action2_page2_ratio',
    'user_user_activity_lsam', 'user_app_launch_rate_f5_resInv', 'user_user_activity_abs_energy',
    'user_action2_page0_ratio', 'user_user_activity_workday_weekend_rate_ratio', 'user_user_activity_rate_b2_resInv',
    'user_app_launch_rate_b0', 'user_user_activity_gap_b6', 'user_video_ratio']
eli_features5 = [
    'user_page2_action5_ratio', 'user_page2_action3_ratio', 'user_video_create_day_f2',
    'user_user_activity_workday_frequency', 'user_action3_page2_ratio', 'user_video_create_day_var_b8',
    'user_video_create_frequency_f2', 'user_user_activity_only_in_weekend', 'user_video_create_frequency_f0',
    'user_video_create_frequency_b6','user_video_create_day_f2_resInv','user_video_create_cid_ce',
    'user_video_create_rate_f4_resInv','user_user_activity_first_time', 'user_video_create_frequency_f4',
    'user_video_create_gap_b11', 'user_video_create_abs_energy', 'user_action3_page4_ratio',
    'user_page1_action3_ratio', 'user_video_create_gap_b5', 'user_video_create_device_type_ratio',
    'user_video_create_rate_f0', 'user_user_activity_day_b4_resInv', 'user_video_create_var_b11',
    'user_page1_action1_ratio', 'user_action1_page3_ratio', 'user_action3_page0_ratio',
    'user_user_activity_mean','user_action1_page4_ratio', 'user_page3_action3_ratio',
    'user_user_activity_mode', 'user_video_create_frequency_b3', 'user_video_create_rate_b3_resInv',
    'user_user_activity_weekend_rate', 'user_user_activity_bent', 'user_user_activity_tras',
    'user_in_author_rate', 'user_app_launch_activity_ratio', 'user_page2_action0_ratio',
    'user_user_activity_last_time', 'user_action2_page2_ratio', 'user_user_activity_lsbm',
    'register_day_device_type_register_ratio', 'user_action2_page0_ratio', 'user_user_activity_workday_weekend_day_ratio',
    'user_app_launch_rbrs', 'user_user_activity_rate_b1_resInv', 'video_author_ratio',
    'user_app_launch_abs_energy', 'user_app_launch_cam', 'user_user_activity_rate_f0_resInv',
    'user_app_launch_rate_f2_resInv', 'user_app_launch_var_b9', 'user_user_activity_rate_b6_resInv',
    'user_app_launch_mod_var', 'register_type_device', 'user_app_launch_rate_b3_resInv']

f_union_all = [
    'user_user_activity_var_b3', 'user_video_create_rate_f4', 'user_action0_page2_ratio',
    'user_action5_page0_ratio', 'user_action3_page3_ratio', 'user_app_launch_rbrs',
    'user_user_activity_var_lt_std', 'user_page1_action4_ratio', 'user_user_activity_day_b7_resInv',
    'user_user_activity_rate_f1', 'user_action2_page1_ratio', 'user_user_activity_frequency_f1',
    'user_app_launch_var_lt_std', 'user_video_create_day_var_b5', 'user_page2_action1_ratio',
    'register_day', 'user_user_activity_workday_weekend_rate_ratio', 'user_page4_action4_ratio',
    'user_action3_page2_ratio', 'user_action5_page1_ratio', 'user_action2_page1',
    'user_page1_action5_ratio', 'user_app_launch_var_b9', 'user_page2_action5_ratio',
    'user_user_activity_max', 'user_user_activity_day_b4_resInv', 'user_action0_page0_ratio',
    'user_user_activity_rate_b2_resInv', 'register_type_device', 'user_video_create_abs_energy',
    'user_page0_ratio', 'user_video_create_var_lt_std', 'user_user_activity_rbrs',
    'user_app_launch_cam', 'user_action4_page2_ratio', 'user_action4_page0_ratio',
    'user_app_launch_rate_b3_resInv', 'user_user_activity_workday_frequency', 'user_user_activity_day_b10', 'user_action_type0_ratio',
    'user_user_activity_median', 'user_user_activity_day_var_b6', 'user_video_create_frequency_f2',
    'user_user_activity_rate_f3', 'user_user_activity_rate_f3_resInv', 'user_action1_page0_ratio',
    'user_action3_page0_ratio', 'user_user_activity_first_time', 'user_user_activity_rate_b9_resInv',
    'user_video_create_day_b3', 'user_user_activity_weekend_frequency', 'user_action1_page3_ratio',
    'user_user_activity_lsam', 'user_video_create_rate_b6', 'user_action0_page1_ratio',
    'user_user_activity_day_b4', 'user_page3_action4_ratio', 'user_page0_action4_ratio',
    'user_video_create_cid_ce', 'user_video_create_frequency_f0', 'user_user_activity_abs_energy',
    'user_user_activity_day_b2', 'user_video_create_rate_f0', 'user_app_launch_rate_b6_resInv',
    'user_video_create_cbm', 'user_video_create_rate_b3', 'user_user_activity_weekend_day',
    'user_user_activity_last_time', 'user_user_activity_mode', 'user_author_rate_resInv',
    'user_user_activity_weekend_rate', 'user_video_create_day_f0', 'user_user_activity_day_b7',
    'user_user_activity_day_var_b9', 'user_video_create_frequency_b3', 'user_app_launch_rate_b9_resInv',
    'user_author_ratio', 'user_page1_action1_ratio', 'user_video_create_rate_b12_resInv',
    'user_video_create_frequency_b9', 'user_action0_page3_ratio', 'user_user_activity_rate_f4_resInv',
    'user_user_activity_day_b6_resInv', 'register_day_device_type_register_ratio', 'user_user_activity_day_f0_resInv',
    'user_app_launch_mod_var', 'user_user_activity_rate_b4_resInv', 'user_action2_page2_ratio',
    'user_user_activity_day_b11_resInv', 'user_user_activity_day_b0', 'user_video_create_day_b9',
    'user_video_create_day_f2_resInv', 'user_page2_action2_ratio', 'video_author_ratio',
    'user_action1_page2_ratio', 'user_user_activity_tras', 'user_user_activity_mod_var',
    'user_app_launch_rate_f2_resInv', 'user_video_create_frequency_f4', 'user_action3_page4_ratio',
    'user_video_create_frequency_b6', 'user_video_create_rate_f0_resInv', 'user_user_activity_var_b9',
    'user_video_create_var_b5', 'user_author_rate', 'user_video_create_gap_b11',
    'user_page1_ratio', 'user_page3_action1_ratio', 'user_video_create_register_type_ratio',
    'user_app_launch_abs_energy', 'user_user_activity_rate_f0_resInv', 'user_user_activity_day_f3_resInv',
    'user_action5_page2_ratio', 'user_action_type4_ratio', 'user_in_author_rate',
    'user_user_activity_workday_weekend_day_ratio', 'user_app_launch_video_ratio', 'user_user_activity_day_f1_resInv',
    'user_app_launch_rate_b8_resInv', 'user_video_create_gap_b8', 'user_user_activity_day_b1_resInv',
    'user_user_activity_day_f0', 'user_user_activity_day_b0_resInv', 'user_page0_action5_ratio',
    'user_video_create_day_b12_resInv', 'user_user_activity_frequency_f3', 'user_user_activity_day_f2',
    'user_user_activity_only_in_weekend', 'user_app_launch_tras', 'user_user_activity_rate_f0',
    'user_user_activity_frequency_f2', 'user_user_activity_rate_f2', 'user_app_launch_rate_f4',
    'user_video_create_rbrs', 'user_page1_action2_ratio', 'user_user_activity_day_var',
    'user_user_activity_day_f4_resInv', 'user_action2_page0_ratio', 'user_video_create_last_time',
    'user_user_activity_min', 'user_user_activity_day_b8', 'user_user_activity_day_b8_resInv',
    'user_app_launch_rate_b0', 'user_app_launch_register_device_ratio', 'user_app_launch_activity_ratio',
    'user_app_launch_rate_b10', 'user_video_create_gap', 'user_action1_page4_ratio',
    'user_video_create_day_var_b11', 'user_video_create_register_device_ratio', 'user_page2_ratio',
    'user_video_create_device_type_ratio', 'user_user_activity_day_f5', 'user_video_create_first_time',
    'user_video_create_device_register_ratio', 'user_page3_action3_ratio', 'user_action2_page4_ratio',
    'device_type_ratio', 'user_app_launch_gap_b9', 'user_page2_action0_ratio',
    'user_page1_action3_ratio', 'user_app_launch_rate_f1', 'user_video_create_min',
    'user_user_activity_day_f4', 'user_action3_page1_ratio', 'user_user_activity_rate_b11_resInv',
    'user_video_create_day_f2', 'user_user_activity_rate_b7_resInv', 'user_user_activity_var_b6',
    'user_video_create_rate_f4_resInv', 'user_app_launch_rate_b10_resInv', 'user_video_create_day_var_b8',
    'user_user_activity_autocorr', 'user_user_activity_rate_b9', 'user_video_create_median',
    'user_app_launch_register_time', 'user_video_create_rate_b3_resInv', 'user_user_activity_rate_b7',
    'user_video_create_rate_f2_resInv', 'user_page4_action0_ratio', 'user_user_activity_prda',
    'user_video_create_rate_b0', 'user_app_launch_workday_rate', 'user_page4_ratio',
    'user_user_activity_rate_b5_resInv', 'user_user_activity_workday_rate', 'user_video_create_prda',
    'user_video_create_var', 'user_video_create_var_b11', 'user_app_launch_rate_b11',
    'user_app_launch_rate_f5', 'user_user_activity_gap', 'user_page3_action0_ratio',
    'user_action4_page3_ratio', 'user_app_launch_rate_f5_resInv', 'user_user_activity_rate_b8_resInv',
    'user_page2_action4_ratio', 'user_user_activity_bent', 'user_page2_action3_ratio',
    'user_video_ratio', 'user_action4_page4_ratio', 'user_video_create_gap_b5',
    'user_video_create_var_b8', 'user_user_activity_rate_b3', 'user_user_activity_gap_b6',
    'user_action_type3_ratio', 'user_user_activity_rate_b11', 'user_user_activity_day_b10_resInv',
    'user_user_activity_day_b9_resInv', 'user_user_activity_lsbm', 'user_user_activity_rate_b6_resInv',
    'user_app_launch_rate_b7_resInv', 'user_user_activity_rate_b1_resInv', 'user_user_activity_mean',
    'user_action4_page1_ratio']
f_keep_all =['user_id', 'label',
    'user_user_activity_day_var_b3','user_user_activity_frequency_b10','user_app_launch_rate_b0_resInv',
    'user_video_create_mode','user_user_activity_rate_f1_resInv','user_user_activity_rate_f5',
    'user_page4_action3_ratio','user_video_create_rate_b9','user_app_launch_rate_b5_resInv',
    'user_user_activity_day_f2_resInv','user_user_activity_frequency_b3','user_app_launch_rate_b4',
    'user_video_create_day_f4_resInv','user_app_launch_rate_b1_resInv','user_user_activity_rate_f4',
    'user_app_launch_mean_change','user_video_create_rate_f2','user_video_create_frequency_b12',
    'user_app_launch_var_b3','user_user_activity_rate_b5','user_user_activity_day_var_b12',
    'user_app_launch_cbm','user_app_launch_autocorr','user_user_activity_frequency_b1',
    'user_user_activity_rate_b10_resInv','user_video_create_mean','user_app_launch_mean',
    'user_app_launch_rate_b9','user_user_activity_day_b5','register_type_device_ratio',
     'user_app_launch_gap','user_user_activity_day_b3','user_video_create_day_b0',
    'user_video_create_day_b6','user_user_activity_frequency_f4','user_user_activity_day_f1',
    'user_app_launch_rate_f2','user_app_launch_rate_b6','user_video_create_day_f0_resInv',
    'user_video_create_day_var','user_page0_action3_ratio','user_user_activity_device_type_ratio',
    'user_user_activity_rate_b0','device_type_register_ratio','user_video_create_rate_b6_resInv',
    'user_user_activity_rate_b1', 'user_video_create_rate_b9_resInv','user_app_launch_gap_b3',
    'user_app_launch_rate_b8','user_user_activity_frequency_b2','user_app_launch_rate_f4_resInv',
    'user_user_activity_rate_b10','user_app_launch_max','user_action_type2_ratio',
    'user_user_activity_day_f3','user_user_activity_rate_f5_resInv','user_app_launch_register_type_ratio',
    'user_video_create_day_b9_resInv','user_page4_action2_ratio','user_app_launch_rate_b7',
    'register_day_register_type_device_ratio','user_user_activity_gap_b12','user_action_type1_ratio',
    'user_video_create_max','user_user_activity_device_register_ratio','user_app_launch_bent',
    'user_app_launch_var_b6','user_app_launch_rate_f0_resInv','user_app_launch_workday_weekend_rate_ratio',
    'user_video_create_rate_b0_resInv','user_user_activity_cid_ce','user_action2_page3_ratio',
    'user_video_create_bent','register_day_device_ratio','user_app_launch_rate_b11_resInv',
    'user_user_activity_frequency_b5','user_video_rate','user_app_launch_device_register_ratio',
    'user_app_launch_weekend_rate','user_app_launch_rate_b2_resInv','user_user_activity_frequency_b11',
    'user_app_launch_rate_b3','user_user_activity_gap_b9','user_video_create_day_f4',
     'user_user_activity_rate_b2','register_type_ratio','user_app_launch_gap_b6',
     'user_user_activity_day_b9','user_app_launch_rate_b1','user_video_create_register_time',
    'user_app_launch_gap_b12','user_user_activity_frequency_b9','user_user_activity_gap_b3',
    'user_user_activity_day_f5_resInv','user_user_activity_var_b12','user_user_activity_frequency_b8',
    'user_app_launch_rate_f3_resInv','user_app_launch_device_type_ratio', 'user_video_create_cam',
    'user_user_activity_day_b5_resInv','user_page0_action1_ratio','user_app_launch_var',
    'user_page3_action2_ratio','user_user_activity_day_b2_resInv','user_user_activity_day_b11',
    'user_user_activity_rate_b8','user_user_activity_register_time', 'user_action0_page4_ratio',
    'user_user_activity_rate_f2_resInv', 'user_app_launch_rate_b5', 'user_page0_action0_ratio',
    'user_user_activity_frequency_f5','user_user_activity_day_b6', 'user_user_activity_register_device_ratio',
    'user_user_activity_frequency_b6','user_user_activity_workday_day','user_video_create_day_b0_resInv',
    'user_app_launch_last_time','user_user_activity_mean_change','user_page3_ratio',
    'user_video_create_lsam','user_user_activity_cam','user_app_launch_only_in_weekend',
    'user_user_activity_frequency_b4','user_app_launch_rate_b4_resInv','user_user_activity_rate_b0_resInv',
    'user_video_create_lsbm','user_app_launch_cid_ce', 'user_user_activity_var',
    'user_user_activity_frequency_b7','user_app_launch_rate_f3','user_page4_action1_ratio',
    'user_user_activity_kurtosis','user_action1_page1_ratio','register_day_type_ratio',
     'user_user_activity_frequency_f0','user_video_create_day_b12','user_app_launch_rate_b2',
    'user_user_activity_cbm','user_app_launch_var_b12','user_user_activity_register_type_ratio',
    'user_video_rate_resInv','user_video_create_day_b3_resInv','user_video_create_tras',
    'user_user_activity_rate_b3_resInv','user_user_activity_rate_b4','user_page0_action2_ratio',
    'user_user_activity_rate_b6','user_app_launch_rate_f0','user_video_create_rate_b12',
    'user_app_launch_median','user_video_create_day_b6_resInv','user_page1_action0_ratio',
    'user_user_activity_day_b3_resInv','user_user_activity_day_b1','user_app_launch_first_time',
    'user_app_launch_rate_f1_resInv']


f_intersect= list(set(eli_features1).intersection(eli_features2))
print("the length of intersected features {}".format(len(f_intersect)))
print("the intersected features: {}".format(f_intersect))

# f_union = list(set(eli_features1+eli_features2+eli_features3+zero_shap_features))
f_union = list(set(eli_features1+eli_features2+eli_features3+eli_features4+eli_features5+zero_shap_features+zero_mi_features+high_collinear_cols))
print("the length of intersected features {}".format(len(f_union)))
print("the intersected features: {}".format(f_union))
